### ISSUE TITLE
Transfer test ARC token to another user

### ISSUE THREAD

**Issue by sponnet** [ArcadeCity/poly-prototype#28]
As a driver I want to be able to send ARC to a rider to immediately pay for a ride. This is the equivalent of paying cash for a ride , but registering the transaction on the blockchain so that the driver and rider reputation can be built up.

Works by displaying a shortcode to the driver containing a transaction batch. ex: 
- transfer 20USD worth of tokens to rider's wallet
- rider creating allowance on his wallet to smart contract
- rider sending 20USD worth of tokens to driver
- displaying confirmation screen for both driver and rider.

**Comment by kikipluche** [comment]
This issue was moved to ArcadeCity/rideshare-client#29
