### ISSUE TITLE
Publishing ride request to the community

### ISSUE THREAD

**Issue by sponnet** [ArcadeCity/poly-prototype#29]
As a rider I want to publish a rideshare request to the ecosystem:
- where do I want to be picked up
- where do I want to be dropped off 
- what is the price i'm offering ( how many coins am I offering for this ride ? )

Implementation :

- A private ride request is encoded in JSON, AES encrypted and uploaded to IPFS - this contains all the data of the user in detail and the IPFS hash is kept on the user's device.
- A public ride request is encoded in JSON and uploaded to IPFS - this contains
  - exact pickup location
  - approximate drop-off location ( 250 m range ? )
  - number of coins offered
  - date of creation
  - the geohash of this request ( = exact location + perimeter of 1000m )
- the IPFS hash of the public ride request is published via whisper to the appropriate geohash channel(s)

**Comment by kikipluche** [comment]
This issue was moved to ArcadeCity/rideshare-client#28
