### ISSUE TITLE
Responding to a ride request ( by driver )

### ISSUE THREAD

**Issue by sponnet** [ArcadeCity/poly-prototype#30]
as a driver - I want to see a list and a map of the current ride requests and offer to pick the rider up.

- Show a list of current requests
- click on request -> showing detail screen with all the details of the ride request.
- 1 tap-accept proposal ( listing you as a candidate driver for this ride )
- or go to negotiation mode
 - offer another price and list yourself as a candidate driver for this ride
 - send an in-app message to rider

**Comment by kikipluche** [comment]
This issue was moved to ArcadeCity/rideshare-client#27
